### PR TITLE
Add US state data from the covid19us package

### PR DESCRIPTION
**Pull request by aedobbyn**
Hi! Thanks for your great package.

I wanted to add a US state-by-state dataset that I think goes more in-depth than the JHU US data.

I recently wrapped up the [COVID Tracking Project](https://covidtracking.com/) data in an [R package](https://github.com/aedobbyn/covid19us) (should be on CRAN very soon).

The data is in wider format than most of the rest of the data in this package:

``` r
(raw <- covid19us::get_states_daily())
#> # A tibble: 701 x 9
#>    date       state positive negative pending death total date_checked       
#>    <date>     <chr>    <int>    <int>   <int> <int> <int> <dttm>             
#>  1 2020-03-18 AK           6      406      NA    NA   412 2020-03-18 20:00:00
#>  2 2020-03-18 AL          46       28      NA     0    74 2020-03-18 20:00:00
#>  3 2020-03-18 AR          33      236      50    NA   319 2020-03-18 20:00:00
#>  4 2020-03-18 AZ          28      148     102     0   278 2020-03-18 20:00:00
#>  5 2020-03-18 CA         611     7981      NA    13  8592 2020-03-18 20:00:00
#>  6 2020-03-18 CO         183     1617      NA     2  1800 2020-03-18 20:00:00
#>  7 2020-03-18 CT          68      125      NA    NA   193 2020-03-18 20:00:00
#>  8 2020-03-18 DC          31      138       1    NA   170 2020-03-18 20:00:00
#>  9 2020-03-18 DE          25       36      NA    NA    61 2020-03-18 20:00:00
#> 10 2020-03-18 FL         314     1225     954     7  2493 2020-03-18 20:00:00
#> # … with 691 more rows, and 1 more variable: request_datetime <dttm>
```

But it can be reshaped to match better:

``` r
suppressPackageStartupMessages(library(dplyr))

raw %>% 
  select(
    state,
    positive,
    death,
    date_checked
  ) %>% 
  rename(
    confirmed = positive,
    Province.State = state,
    date = date_checked
  ) %>% 
  mutate(
    Country.Region = "US",
    Lat = NA_real_,
    Long = NA_real_
  ) %>% 
  tidyr::pivot_longer(
    confirmed:death,
    names_to = "type"
  ) %>% 
  rename(
    cases = value
  ) %>% 
  select(
    Province.State,
    Country.Region,
    Lat,
    Long,
    date,
    cases,
    type
  ) %>% 
  tidyr::drop_na(cases)
#> # A tibble: 815 x 7
#>    Province.State Country.Region   Lat  Long date                cases type     
#>    <chr>          <chr>          <dbl> <dbl> <dttm>              <int> <chr>    
#>  1 AK             US                NA    NA 2020-03-18 20:00:00     6 confirmed
#>  2 AL             US                NA    NA 2020-03-18 20:00:00    46 confirmed
#>  3 AL             US                NA    NA 2020-03-18 20:00:00     0 death    
#>  4 AR             US                NA    NA 2020-03-18 20:00:00    33 confirmed
#>  5 AZ             US                NA    NA 2020-03-18 20:00:00    28 confirmed
#>  6 AZ             US                NA    NA 2020-03-18 20:00:00     0 death    
#>  7 CA             US                NA    NA 2020-03-18 20:00:00   611 confirmed
#>  8 CA             US                NA    NA 2020-03-18 20:00:00    13 death    
#>  9 CO             US                NA    NA 2020-03-18 20:00:00   183 confirmed
#> 10 CO             US                NA    NA 2020-03-18 20:00:00     2 death    
#> # … with 805 more rows
```

<sup>Created on 2020-03-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

We could also attach lat/longs with the Google Maps API through the `ggmap` package. That could be stored as package data and joined on using the state abbreviation.

Interested to hear what you think!

### CODE REVIEW

**Comment by aedobbyn** [comment]
^ Run failed because `covid19us` is not yet on CRAN but is listed under Imports in the `DESCRIPTION`

**Comment by RamiKrispin** [comment]
Hi @aedobbyn thanks for the pull request! 

I already started to [pull](https://github.com/RamiKrispin/coronavirus/blob/master/data_raw/us_data.R) this dataset couple of days ago but did not have the time work on it yet. I am mainly want to be able to pull this data with the `update_datasets` function. Any suggestions about how it can be done from your package?

Does your package is going to have county-level data?

Adding Google Maps API features sounds great, but I would check with @jebyrnes if this feature does not already exist [here](https://ramikrispin.github.io/coronavirus/articles/spatial_coronavirus.html)

Thanks!
Rami

**Comment by aedobbyn** [comment]
Great! Yep, I stuck [these lines](https://github.com/RamiKrispin/coronavirus/pull/22/files#diff-eafbf7d27bcc9e997772628c06a0480fR122-R124) into `update_datasets`.

Could also stick a 

```
if (identical(df5, coronavirus::covid_us_states)){
    print("The covid_us_states dataset is up-to-date")
  }
```

in there too if you want. 

The package has all the endpoints that the COVID Tracking Project makes available, but as of now the `/counties` endopint only includes info about counties, not counts of cases. Also, county info is sort of sparse at the moment; mostly just in the hardest-hit areas.

``` r
library(covid19us)
get_counties_info()
#> # A tibble: 11 x 8
#>    state county covid_19_site data_site main_site twitter pui  
#>    <chr> <chr>  <chr>         <lgl>     <chr>     <lgl>   <chr>
#>  1 CA    Los A… http://publi… NA        <NA>      NA      No d…
#>  2 NY    Westc… https://heal… NA        <NA>      NA      No d…
#>  3 WA    King   https://www.… NA        <NA>      NA      No d…
#>  4 WA    Snoho… https://www.… NA        <NA>      NA      All …
#>  5 WA    Grant  http://grant… NA        <NA>      NA      No d…
#>  6 WA    Jeffe… https://www.… NA        <NA>      NA      All …
#>  7 WA    Pierce https://www.… NA        <NA>      NA      Only…
#>  8 WA    Clark  https://www.… NA        <NA>      NA      All …
#>  9 WA    Kitti… https://www.… NA        <NA>      NA      No d…
#> 10 CA    Contr… https://www.… NA        https://… NA      <NA> 
#> 11 CA    Alame… http://www.a… NA        http://w… NA      <NA> 
#> # … with 1 more variable: request_datetime <dttm>
```

<sup>Created on 2020-03-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by aedobbyn** [comment]
As far as the spatial stuff, @jebyrnes it looks like we need `Lat` and `Long` [here](https://github.com/RamiKrispin/coronavirus/blob/61a22a289465050f9594699b10d807235fac8172/R/coronavirus_spatial.R#L60) for `sf::st_as_sf` but I could be wrong?

**Comment by jebyrnes** [comment]
Indeed, something with coordinates is needed. Then again, if this is just state level data, can it be joined to the output of ne_states() from rnaturalearth? If the state names match, a join there would make it instantly spatial with polygons.

**Comment by aedobbyn** [comment]
Yeah @jebyrnes I think that would work!

``` r
library(magrittr)

rnaturalearth::ne_states(country = "United States of America") %>%
  tibble::glimpse()
#> Formal class 'SpatialPolygonsDataFrame' [package "sp"] with 5 slots
#>   ..@ data       :'data.frame':  51 obs. of  83 variables:
#>   .. ..$ featurecla: chr [1:51] "Admin-1 scale rank" "Admin-1 scale rank" "Admin-1 scale rank" "Admin-1 scale rank" ...
#>   .. ..$ scalerank : int [1:51] 2 2 2 2 2 2 2 2 2 2 ...
#>   .. ..$ adm1_code : chr [1:51] "USA-3514" "USA-3519" "USA-3518" "USA-3515" ...
#>   .. ..$ diss_me   : int [1:51] 3514 3519 3518 3515 3516 3562 3561 3550 3538 3559 ...
#>   .. ..$ iso_3166_2: chr [1:51] "US-MN" "US-WA" "US-ID" "US-MT" ...
#>   .. ..$ wikipedia : chr [1:51] "http://en.wikipedia.org/wiki/Minnesota" "http://en.wikipedia.org/wiki/Washington_(state)" "http://en.wikipedia.org/wiki/Idaho" "http://en.wikipedia.org/wiki/Montana" ...
#>   .. ..$ iso_a2    : chr [1:51] "US" "US" "US" "US" ...
#>   .. ..$ adm0_sr   : int [1:51] 1 6 1 1 1 1 6 1 1 3 ...
#>   .. ..$ name      : chr [1:51] "Minnesota" "Washington" "Idaho" "Montana" ...
#>   .. ..$ name_alt  : chr [1:51] "MN|Minn." "WA|Wash." "ID|Idaho" "MT|Mont." ...
#>   .. ..$ name_local: chr [1:51] NA NA NA NA ...
#>   .. ..$ type      : chr [1:51] "State" "State" "State" "State" ...
#>   .. ..$ type_en   : chr [1:51] "State" "State" "State" "State" ...
#>   .. ..$ code_local: chr [1:51] "US27" "US53" "US16" "US30" ...
#>   .. ..$ code_hasc : chr [1:51] "US.MN" "US.WA" "US.ID" "US.MT" ...
#>   .. ..$ note      : chr [1:51] NA NA NA NA ...
#>   .. ..$ hasc_maybe: chr [1:51] NA NA NA NA ...
#>   .. ..$ region    : chr [1:51] "Midwest" "West" "West" "West" ...
#>   .. ..$ region_cod: chr [1:51] NA NA NA NA ...
#>   .. ..$ provnum_ne: int [1:51] 0 0 0 0 0 0 0 0 0 0 ...
#>   .. ..$ gadm_level: int [1:51] 1 1 1 1 1 1 1 1 1 1 ...
#>   .. ..$ check_me  : int [1:51] 20 20 20 20 20 20 20 20 20 20 ...
#>   .. ..$ datarank  : int [1:51] 1 1 1 1 1 1 1 1 1 1 ...
#>   .. ..$ abbrev    : chr [1:51] "Minn." "Wash." "Idaho" "Mont." ...
#>   .. ..$ postal    : chr [1:51] "MN" "WA" "ID" "MT" ...
#>   .. ..$ area_sqkm : int [1:51] 0 0 0 0 0 0 0 0 0 0 ...
#>   .. ..$ sameascity: int [1:51] NA NA NA NA NA NA NA NA NA NA ...
#>   .. ..$ labelrank : int [1:51] 0 0 0 0 0 0 0 0 0 0 ...
#>   .. ..$ name_len  : int [1:51] 9 10 5 7 12 8 5 4 13 8 ...
#>   .. ..$ mapcolor9 : int [1:51] 1 1 1 1 1 1 1 1 1 1 ...
#>   .. ..$ mapcolor13: int [1:51] 1 1 1 1 1 1 1 1 1 1 ...
#>   .. ..$ fips      : chr [1:51] "US27" "US53" "US16" "US30" ...
#>   .. ..$ fips_alt  : chr [1:51] NA NA NA NA ...
#>   .. ..$ woe_id    : int [1:51] 2347582 2347606 2347571 2347585 2347593 2347581 2347578 2347594 2347588 2347591 ...
#>   .. ..$ woe_label : chr [1:51] "Minnesota, US, United States" "Washington, US, United States" "Idaho, US, United States" "Montana, US, United States" ...
#>   .. ..$ woe_name  : chr [1:51] "Minnesota" "Washington" "Idaho" "Montana" ...
#>   .. ..$ latitude  : num [1:51] 46.1 47.5 43.8 47 47.5 ...
#>   .. ..$ longitude : num [1:51] -93.4 -120.4 -114.1 -110 -100.3 ...
#>   .. ..$ sov_a3    : chr [1:51] "US1" "US1" "US1" "US1" ...
#>   .. ..$ adm0_a3   : chr [1:51] "USA" "USA" "USA" "USA" ...
#>   .. ..$ adm0_label: int [1:51] 2 2 2 2 2 2 2 2 2 2 ...
#>   .. ..$ admin     : chr [1:51] "United States of America" "United States of America" "United States of America" "United States of America" ...
#>   .. ..$ geonunit  : chr [1:51] "United States of America" "United States of America" "United States of America" "United States of America" ...
#>   .. ..$ gu_a3     : chr [1:51] "USA" "USA" "USA" "USA" ...
#>   .. ..$ gn_id     : int [1:51] 5037779 5815135 5596512 5667009 5690763 5001836 4971068 5165418 5090174 5128638 ...
#>   .. ..$ gn_name   : chr [1:51] "Minnesota" "Washington" "Idaho" "Montana" ...
#>   .. ..$ gns_id    : int [1:51] -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
#>   .. ..$ gns_name  : chr [1:51] NA NA NA NA ...
#>   .. ..$ gn_level  : int [1:51] 1 1 1 1 1 1 1 1 1 1 ...
#>   .. ..$ gn_region : chr [1:51] NA NA NA NA ...
#>   .. ..$ gn_a1_code: chr [1:51] "US.MN" "US.WA" "US.ID" "US.MT" ...
#>   .. ..$ region_sub: chr [1:51] "West North Central" "Pacific" "Mountain" "Mountain" ...
#>   .. ..$ sub_code  : chr [1:51] NA NA NA NA ...
#>   .. ..$ gns_level : int [1:51] -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
#>   .. ..$ gns_lang  : chr [1:51] NA NA NA NA ...
#>   .. ..$ gns_adm1  : chr [1:51] NA NA NA NA ...
#>   .. ..$ gns_region: chr [1:51] NA NA NA NA ...
#>   .. ..$ min_label : num [1:51] 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 ...
#>   .. ..$ max_label : num [1:51] 7.5 7.5 7.5 7.5 7.5 7.5 7.5 7.5 7.5 7.5 ...
#>   .. ..$ min_zoom  : num [1:51] 2 2 2 2 2 2 2 2 2 2 ...
#>   .. ..$ wikidataid: chr [1:51] "Q1527" "Q1223" "Q1221" "Q1212" ...
#>   .. ..$ name_ar   : chr [1:51] NA NA NA NA ...
#>   .. ..$ name_bn   : chr [1:51] NA NA NA NA ...
#>   .. ..$ name_de   : chr [1:51] "Minnesota" "Washington" "Idaho" "Montana" ...
#>   .. ..$ name_en   : chr [1:51] "Minnesota" "Washington" "Idaho" "Montana" ...
#>   .. ..$ name_es   : chr [1:51] "Minnesota" "Washington" "Idaho" "Montana" ...
#>   .. ..$ name_fr   : chr [1:51] "Minnesota" "État de Washington" "Idaho" "Montana" ...
#>   .. ..$ name_el   : chr [1:51] NA NA NA NA ...
#>   .. ..$ name_hi   : chr [1:51] NA NA NA NA ...
#>   .. ..$ name_hu   : chr [1:51] "Minnesota" "Washington" "Idaho" "Montana" ...
#>   .. ..$ name_id   : chr [1:51] "Minnesota" "Washington" "Idaho" "Montana" ...
#>   .. ..$ name_it   : chr [1:51] "Minnesota" "Washington" "Idaho" "Montana" ...
#>   .. ..$ name_ja   : chr [1:51] NA NA NA NA ...
#>   .. ..$ name_ko   : chr [1:51] NA NA NA NA ...
#>   .. ..$ name_nl   : chr [1:51] "Minnesota" "Washington" "Idaho" "Montana" ...
#>   .. ..$ name_pl   : chr [1:51] "Minnesota" "Waszyngton" "Idaho" "Montana" ...
#>   .. ..$ name_pt   : chr [1:51] "Minnesota" "Washington" "Idaho" "Montana" ...
#>   .. ..$ name_ru   : chr [1:51] NA NA NA NA ...
#>   .. ..$ name_sv   : chr [1:51] "Minnesota" "Washington" "Idaho" "Montana" ...
#>   .. ..$ name_tr   : chr [1:51] "Minnesota" "Vasington" "Idaho" "Montana" ...
#>   .. ..$ name_vi   : chr [1:51] "Minnesota" "Washington" "Idaho" "Montana" ...
#>   .. ..$ name_zh   : chr [1:51] NA NA NA NA ...
#>   .. ..$ ne_id     : chr [1:51] "1159315297" "1159309547" "1159315339" "1159315333" ...
#>   ..@ polygons   :List of 51
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   .. ..$ :Formal class 'Polygons' [package "sp"] with 5 slots
#>   ..@ plotOrder  : int [1:51] 17 16 4 14 15 37 13 33 38 36 ...
#>   ..@ bbox       : num [1:2, 1:2] -179.1 18.9 179.8 71.4
#>   .. ..- attr(*, "dimnames")=List of 2
#>   ..@ proj4string:Formal class 'CRS' [package "sp"] with 1 slot
```

<sup>Created on 2020-03-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by aedobbyn** [comment]
@RamiKrispin what do you think about the format of the data? Should we take it to long to more closely match the JHU data?

Also, another potentially useful data source if there are any gaps in JHU is [the WHO's](https://covid.ourworldindata.org/data/who/full_data.csv).

**Comment by RamiKrispin** [comment]
Tasked moved to the [Covid19R](https://github.com/Covid19R)

**Pull request closed without merging**
