### PR TITLE
Dev jebyrnes

### PR DESCRIPTION
**Pull request by jebyrnes**
I made a *slew* of changes on data updating for the JHU dataset. These included

1. Moving the update script fully into /R as a function update_coronavirus_raw() that can be called from within the package or via the data update script.

2. Added spatial joining to get correct names for countries and regions. Retained JHU data with 'JHU.' columns.

3. Added warning info on update_data_raw that the downloaded data is not QC-ed. Hence, update_datasets is the preferred way to update data that is known to be solid.

4. Updated vignette and pkgdown website.

5. Also now have the sf object as well as some reference sf objects saved in data

6. As this is a big change to the data, incremented the package version number appropriately.

TODO
- I think the sf object can also be put into your QC-ed data archive, and hence used by `update_datasets()`

### CODE REVIEW

**Comment by RamiKrispin** [comment]
Thanks @jebyrnes! will pull it on the command line and test

**Comment by jebyrnes** [comment]
Note - I just added coronadatascrapper.com as a data source to create a separate dataset. Would be v. useful to add.

IMHO, after adding it and the other data source from the other PR, might be worth giving us marching orders to get 0.2 onto CRAN!

**Comment by RamiKrispin** [comment]
@jebyrnes added a package tracker https://github.com/RamiKrispin/coronavirus/projects/1

**Comment by RamiKrispin** [comment]
Tasked moved to the [Covid19R](https://github.com/Covid19R)

**Pull request closed without merging**
