### PR TITLE
Adding ability to dynamically update coronavirus dataset

### PR DESCRIPTION
**Pull request by jebyrnes**
As it can be a PITA to update the package before working with it, I added a function to pull an updated version of the dataset. Yes, it increases dependencies, as it does all of the processing, but, most of these are tools that the users are likely using anyway? I updated the pkgdown website as well, just to keep pace. Feel free to accept, or reject and do it a different way. Thought it might be helpful, though!

### CODE REVIEW

**Comment by piccolbo** [comment]
Hey I tried `update_coronavirus` and I found a few problems

1. There's a country Iran and another Islamic Republic of Iran
2. Hong Kong and Hong Kong SAR
3. Palestine and occupied palestinian territory
4. Moldova and Republic of Moldova
5. Russia and Russian federation
6.Macau and Macao SAR
7. Taiwan and Taipei

I don't want to enter any thorny political issues and  I will use whichever name people are most comfortable with, but I am worried about duplication of data or splitting of totals. Could you look into this? (BTW, I have no power to merge even if you resolve these issues) Thanks!

**Comment by piccolbo** [comment]
I am using this. Previous comment on name changes seems to be unfounded -- there have been name changes but they have been propagated retroactively.

**Comment by piccolbo** [comment]
Noticed an outlandish value for 3/10 for the US (over 1000 confirmed for one day). I noticed that the data is reported at the state and county level. I am summing up everything clearly overcounting. Any ideas what's going on? How to get a country count? Did not notice the problem before.

**Comment by piccolbo** [comment]
The US confirmed numbers vary wildly from 0 to 1000 and back in the last few days. I don't see that in RamiKrispin data. The current us total, cumulative from the beginning of recordkeeping,is just above 1000.

**Comment by jebyrnes** [comment]
These should all be problems with the data sources, no? Not the aggregation? Might be worth filing issues there.

**Comment by piccolbo** [comment]
Sorry I wasn't clear. Don't see those data problems using the package you forked, RamiKrisnan/coronavirus. So the data source is the same.

**Comment by jebyrnes** [comment]
Huh - can you show me a reprex? I literally just moved the script that updated the data into an R file.

**Comment by jebyrnes** [comment]
``` r
library(coronavirus)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

coronavirus <- update_coronavirus() 
#> [1] "Reading confirmed..."
#> [1] "Reading deaths..."
#> [1] "Reading recovery..."

coronavirus %>% filter(Country.Region=="US") %>%
  group_by(type) %>%
  summarize(min_cases = min(cases),
            max_cases = max(cases),
            total_cases = sum(cases))
#> # A tibble: 3 x 4
#>   type      min_cases max_cases total_cases
#>   <chr>         <int>     <int>       <int>
#> 1 confirmed        -5       267        1670
#> 2 death             1        23          56
#> 3 recovered         1         2          15
```

<sup>Created on 2020-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by piccolbo** [comment]
Sure thing
```
> coronavirus %>%
    group_by(Country.Region, type, date) %>%
    summarise(cases = as.double(sum(cases))) %>% filter(Country.Region == "US") %>% filter(cases == max(cases))
# A tibble: 3 x 4
# Groups:   Country.Region, type [3]
  Country.Region type      date       cases
  <chr>          <chr>     <date>     <dbl>
1 US             confirmed 2020-03-10  1086
2 US             death     2020-03-10    34
3 US             recovered 2020-03-10     8
```

With RamiKrisnan data, same snippet

```
  Country.Region type      date       cases
  <chr>          <chr>     <date>     <dbl>
1 US             confirmed 2020-03-10   193
2 US             death     2020-03-10     6
3 US             recovered 2020-02-09     3
```
That's consistent with what was in the news.

**Comment by jebyrnes** [comment]
Can you provide a link to that data source? That's clearly wrong, as we had 500 total confirmed cases as of Monday, and it's gone quite a bit up since then.

**Comment by piccolbo** [comment]
The data source is the rda file in the data dir in @RamiKrispin repo, master branch. I did a straight load on it. You may have not noticed that I grouped by date so that is not a cumulative number over time, it's consistent with the news and what the johns hopkins coronavirus dashboard said on that day.
Sorry if it's operator error, it just doesn't add up on my side.

**Comment by piccolbo** [comment]
Just stumbled in the new that we passed the 1000 cumulative mark today:
https://www.theguardian.com/us-news/2020/mar/11/us-briefing-biden-wins-big-again-us-covid-19-cases-pass-1000-and-mh17

**Comment by RamiKrispin** [comment]
Hi @jebyrnes, @piccolbo the error in the data pull is due to changes in the countries labels and duplication in the data. Yesterday there was a change in the structure of the US data that made the jump in the US. I made some changes in the script that pull the data, and it seems that I will have to continuously monitor the changes until it will reach some level of maturity. 

@jebyrnes I am working on the pull request, I will do it on my command line to avoid solving the confilics on the html files.

Thanks!
Rami

**Comment by piccolbo** [comment]
I am not sure I am following, does that explain discrepancy between you and @jebyrnes? Because a) We are talking about a US-specific problem b) There are some strange numbers in his that I haven't seen in yours. Thanks!

**Comment by RamiKrispin** [comment]
The issue with the negative values is related to update of the cumulative values based on new information. See the last comment on the following [issue](https://github.com/CSSEGISandData/COVID-19/issues/285).

The second cause, so far, for unusual values, related to change in the labeling system over time. For example, today, the labeling of China was changed from `Mainland China` to `China`. So now, for instance, for the [confirmed cases](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv#L2), province `Anhui` have 990 cumulative values until yesterday and 0 from today (raw 2) and in raw 357 will have 0s until yesterday and 990 from today. Running the code without making any modification, will show two values for this province, one with 990 new cases and other with -990. Here is the output:

```
> tail(coronavirus)
# A tibble: 6 x 7
  Province.State Country.Region   Lat  Long date       cases type     
  <chr>          <chr>          <dbl> <dbl> <date>     <dbl> <chr>    
1 Xinjiang       China           41.1  85.2 2020-03-11    73 recovered
2 Xinjiang       Mainland China  41.1  85.2 2020-03-11   -73 recovered
3 Yunnan         China           25.0 101.  2020-03-11   170 recovered
4 Yunnan         Mainland China  25.0 101.  2020-03-11  -170 recovered
5 Zhejiang       China           29.2 120.  2020-03-11  1195 recovered
6 Zhejiang       Mainland China  29.2 120.  2020-03-11 -1191 recovered
```

**Comment by piccolbo** [comment]
Please see example above, the problem is US numbers that are too big. A 3/10 confirmed over 1000 with this fork. It's below 200 in your data.

**Comment by RamiKrispin** [comment]
Here are the values I am receiving from the US from the most recent pull:
```
# A tibble: 27 x 2
   date       total
   <date>     <dbl>
 1 2020-01-22     1
 2 2020-01-24     1
 3 2020-01-26     3
 4 2020-01-31     2
 5 2020-02-01     1
 6 2020-02-03     3
 7 2020-02-09     3
 8 2020-02-11     1
 9 2020-02-13     1
10 2020-02-21     4
11 2020-02-24    36
12 2020-02-25     1
13 2020-02-26     6
14 2020-02-27     1
15 2020-02-28     3
16 2020-02-29     9
17 2020-03-01     6
18 2020-03-02    29
19 2020-03-03    21
20 2020-03-04    35
21 2020-03-05    69
22 2020-03-06    52
23 2020-03-07   139
24 2020-03-08   119
25 2020-03-09    67
26 2020-03-10   199
27 2020-03-11   295
```

**Comment by piccolbo** [comment]
That's aggregate for all states? I have 193 for 3/10 with your data, with @jebyrnes' it's 1086. Neither matches exactly, but  the latter is not even close. Code is posted here 6 hours ago. I am puzzled.

**Comment by RamiKrispin** [comment]
I think it is close enough with this https://www.worldometers.info/coronavirus/country/us/

**Comment by piccolbo** [comment]
We have two numbers ~200 and ~1000 and you write "it is close enough". Which one? worldometer count is cumulative, please don't compare oranges and apples.

**Comment by piccolbo** [comment]
What we are focusing on is the confirmed new cases for US on 3/10.

**Comment by jebyrnes** [comment]
Would it be useful to abandon the name designations, if duplicates are causing a problem, do a spatial join with something like ne_countries() from rnaturalearth, and then filter on duplicate rows?

**Comment by piccolbo** [comment]
@jebyrnes I'd rather first understand positively what the problem is and where the diff with @RamiKrispin 's data is coming from. I looked at the data and it is obviously redundant,  with state, county, and even city level if I understand right, and then one-offs like ships. Is the Diamond Princess included in CA or not? In Alameda  County, where it is now? Is Alameda County included in CA? And there isn't a column with detail level, that says this is a state, this is a county. You have to parse the name. It's a mess. But somehow @RamiKrispin  is not double-counting when creating his coronavirus.rda. I will read his code today and try to figure it out myself.

As far as joins, I tried something similar with demographics data (not familiar with rnaturalearth) and run immediately into trouble because of the non-standard designations like Mainland China. Hopefully you won't

**Comment by jebyrnes** [comment]
Oh, indeed, that's why I'm doing spatial joins with st_join - no reliance on names.  See coronavirus_spatial() in this branch. FYI, @piccolbo, my students love your app! They just sent it around on our course mailing list.

**Comment by piccolbo** [comment]
OK,  the spatial stuff looks interesting for map making, but sorry it doesn't belong to the same pull request. Let's get dynamic update right here, and do the spatial stuff in the next PR. This is sw engineer 101 guys.

**Comment by piccolbo** [comment]
Hey @jebyrnes thanks for your and your students'kind words.   I get now you are using coordinates  but I don't see how that solves the ambiguous aggregation level. xx,yy is in Alameda County, CA  in ca and in US. I am  missing what part?

**Comment by jebyrnes** [comment]
See https://gist.github.com/jebyrnes/2271a9898bfb39992c98e02ab377672e - st_join() compares lat/long to a polygons, and then merges it with the polygons. Basically, point overlap rather than any string matching. I'm using rnaturalearth as it has a lot of standardized administrative boundaries on it, so we don't have to rely on the information in this data, as it is non-standard.

**Comment by piccolbo** [comment]
That's my point, that even with the point resolution machinery, you can't infer the aggregation level. You would need the boundaries a count applies to.

**Comment by piccolbo** [comment]
Like take 34, 120 Is that a county, state or country? It's all three. How do you get the level to make correct rollups?

**Comment by jebyrnes** [comment]
Right! Which is what you can get from your polygon shapefile - the county, state, and country information, and then you can make aggregation choices from there. In the gist I linked to, it's looking at US states, for example. And aggregates at the state level based on point information.

**Comment by piccolbo** [comment]
Which line exactly detects if a count is county or state level? Sorry don't get it. And @RamiKrispin count was correct without all this additional machinery. Let's keep it simple.

**Comment by RamiKrispin** [comment]
Here is an update about the US data issue - https://github.com/CSSEGISandData/COVID-19/issues/590

**Pull request merged**
